"""
Hardcoded reference lists extracted from:
Entry Form - Allcomers Meet #3 2026.xlsx

NOTE (style-based filtering):
- In "Event Codes (updated)", some Event Code cells are visually blacked out.
- Those blacked-out codes are treated as "NOT INCLUDED" and are excluded from EVENTS.

Generated on: 2026-03-01T10:41:28
"""

# Entry table headers
ENTRY_HEADERS = ['No',
 'Last Name',
 'First Name',
 'Gender\n(M or F)',
 'Birth Date (DD/MM/YYYY)',
 'IC Number \n(last 4 digit)',
 'Unique ID',
 'Nationality',
 'Contact Number',
 'Email',
 'Team Code',
 'Team Name',
 'Event Code',
 'Event Division\n(1 - 8)',
 'Season Best',
 'Emergency Contact Name',
 'Emergency Contact Number',
 'Coach Full Name',
 'PAR Q\n(Y/N)']

# Team reference
TEAMS = [{'team_code': 'ACSB', 'team_name': 'ACS Barker'},
 {'team_code': 'AAC', 'team_name': 'ActiveSG Academies & Club'},
 {'team_code': 'ADP', 'team_name': 'Admiralty Primary School'},
 {'team_code': 'ADSS', 'team_name': 'Admiralty Secondary School'},
 {'team_code': 'AIC', 'team_name': 'Asian Inter-Clubs Athletics Alliance Singapore'},
 {'team_code': 'AIP', 'team_name': 'Ahmad Ibrahim Primary School'},
 {'team_code': 'AIS', 'team_name': 'Ahmad Ibrahim Secondary School'},
 {'team_code': 'ATS', 'team_name': 'Ai Tong School'},
 {'team_code': 'ALP', 'team_name': 'Alexandra Primary School'},
 {'team_code': 'AGP', 'team_name': 'Anchor Green Primary School'},
 {'team_code': 'AJC', 'team_name': 'Anderson JC'},
 {'team_code': 'APS', 'team_name': 'Anderson Primary School'},
 {'team_code': 'ASGC', 'team_name': 'Anderson Secondary School'},
 {'team_code': 'AMK', 'team_name': 'Ang Mo Kio Primary School'},
 {'team_code': 'AMKS', 'team_name': 'Ang Mo Kio Secondary School'},
 {'team_code': 'ACJC', 'team_name': 'Anglo Chinese Junior College'},
 {'team_code': 'ACSI', 'team_name': 'Anglo‑Chinese School (Indep)'},
 {'team_code': 'ACST', 'team_name': 'Anglo‑Chinese School (International)'},
 {'team_code': 'ACSJ', 'team_name': 'Anglo-Chinese School (Junior)'},
 {'team_code': 'ACSP', 'team_name': 'Anglo-Chinese School (Primary)'},
 {'team_code': 'ANG', 'team_name': 'Angsana Primary School'},
 {'team_code': 'BEA', 'team_name': 'Beacon Primary School'},
 {'team_code': 'BTY', 'team_name': 'Beatty Secondary School'},
 {'team_code': 'BGP', 'team_name': 'Bedok Green Primary School'},
 {'team_code': 'BG', 'team_name': 'Bedok Green Secondary School'},
 {'team_code': 'BV', 'team_name': 'Bedok View Sec School'},
 {'team_code': 'BDM', 'team_name': 'Bendemeer Primary School'},
 {'team_code': 'BS', 'team_name': 'Bendemeer Secondary School'},
 {'team_code': 'BPSS', 'team_name': 'Bishan Park Secondary School'},
 {'team_code': 'BRP', 'team_name': 'Blangah Rise Primary School'},
 {'team_code': 'BLG', 'team_name': 'Boon Lay Garden Primary School'},
 {'team_code': 'BPJ', 'team_name': 'Bukit Panjang Primary School'},
 {'team_code': 'BTP', 'team_name': 'Bukit Timah Primary School'},
 {'team_code': 'BTV', 'team_name': 'Bukit View Primary School'},
 {'team_code': 'CPS', 'team_name': 'Canberra Primary School'},
 {'team_code': 'CCP', 'team_name': 'Canossa Primary School'},
 {'team_code': 'CAN', 'team_name': 'Cantonment Primary School'},
 {'team_code': 'CASU', 'team_name': 'Casuarina Primary School'},
 {'team_code': 'CH', 'team_name': 'Catholic High School'},
 {'team_code': 'CHSP', 'team_name': 'Catholic High School (Primary)'},
 {'team_code': 'CJC', 'team_name': 'Catholic Junior College'},
 {'team_code': 'CG', 'team_name': 'Cedar Girls Secondary School'},
 {'team_code': 'CDP', 'team_name': 'Cedar Primary School'},
 {'team_code': 'CCS', 'team_name': 'Changkat Changi Secondary Sch'},
 {'team_code': 'CKP', 'team_name': 'Changkat Primary School'},
 {'team_code': 'CDS', 'team_name': 'Chestnut Drive Sec Sch'},
 {'team_code': 'KTC', 'team_name': 'CHIJ (Katong) Primary'},
 {'team_code': 'IJK', 'team_name': 'CHIJ (Kellock)'},
 {'team_code': 'KC', 'team_name': 'Chij Katong Convent'},
 {'team_code': 'OLGC', 'team_name': 'CHIJ Our Lady of Good Counsel'},
 {'team_code': 'OLN', 'team_name': 'CHIJ Our Lady of the Nativity'},
 {'team_code': 'OLQP', 'team_name': 'CHIJ Our Lady Queen of Peace'},
 {'team_code': 'IJP', 'team_name': 'CHIJ Primary (Toa Payoh)'},
 {'team_code': 'HIJ', 'team_name': 'Chij Secondary (Toa Payoh)'},
 {'team_code': 'STC', 'team_name': "Chij St Theresa's Convent"},
 {'team_code': 'SNG', 'team_name': "Chij St. Nicholas Girls'"},
 {'team_code': 'SNGP', 'team_name': "CHIJ St. Nicholas Girls' School (Primary)"},
 {'team_code': 'CFS', 'team_name': 'Chongfu School'},
 {'team_code': 'CZP', 'team_name': 'Chongzheng Primary School'},
 {'team_code': 'CHR', 'team_name': 'Christ Church Secondary School'},
 {'team_code': 'CCKP', 'team_name': 'Chua Chu Kang Primary School'},
 {'team_code': 'CCK', 'team_name': 'Chua Chu Kang Secondary School'},
 {'team_code': 'CCHM', 'team_name': 'Chung Cheng High School (Main)'},
 {'team_code': 'CTP', 'team_name': 'Clementi Primary School'},
 {'team_code': 'ZOOM', 'team_name': 'Club Zoom'},
 {'team_code': 'CWSS', 'team_name': 'Commonwealth Sec Sch'},
 {'team_code': 'CVP', 'team_name': 'Compassvale Primary School'},
 {'team_code': 'CCP', 'team_name': 'Concord Primary School'},
 {'team_code': 'COR', 'team_name': 'Corporation Primary School'},
 {'team_code': 'CAA', 'team_name': 'Cougar Athletic Association'},
 {'team_code': 'CGS', 'team_name': "Crescent Girls' School"},
 {'team_code': 'CRS', 'team_name': 'Crest Secondary School'},
 {'team_code': 'DMP', 'team_name': 'Damai Primary School'},
 {'team_code': 'DZP', 'team_name': 'Dazhong Primary School'},
 {'team_code': 'DLS', 'team_name': 'De La Salle School'},
 {'team_code': 'DYSS', 'team_name': 'Deyi Secondary School'},
 {'team_code': 'DUC', 'team_name': 'Dulwich College'},
 {'team_code': 'DHS', 'team_name': 'Dunman High School'},
 {'team_code': 'ESP', 'team_name': 'East Spring Primary School'},
 {'team_code': 'EFP', 'team_name': 'Edgefield Primary School'},
 {'team_code': 'EPP', 'team_name': 'Elias Park Primary School'},
 {'team_code': 'ENDP', 'team_name': 'Endeavour Primary School'},
 {'team_code': 'EC', 'team_name': 'Erovra Club'},
 {'team_code': 'EGS', 'team_name': 'Eunoia Junior College'},
 {'team_code': 'EVGP', 'team_name': 'Evergreen Primary School'},
 {'team_code': 'EJC', 'team_name': 'Evergreen Secondary School'},
 {'team_code': 'FTS', 'team_name': 'Fast Track Sports'},
 {'team_code': 'FAC', 'team_name': 'Flash Athletic Club'},
 {'team_code': 'FMP', 'team_name': 'Fairfield Methodist School (Primary)'},
 {'team_code': 'FPP', 'team_name': 'Farrer Park Primary School'},
 {'team_code': 'FSP', 'team_name': 'Fengshan Primary School'},
 {'team_code': 'FVP', 'team_name': 'Fernvale Primary School'},
 {'team_code': 'FTP', 'team_name': 'First Toa Payoh Primary School'},
 {'team_code': 'FTA', 'team_name': 'Fortius Athletics'},
 {'team_code': 'FRP', 'team_name': 'Frontier Primary School'},
 {'team_code': 'FCP', 'team_name': 'Fuchun Primary School'},
 {'team_code': 'FC', 'team_name': 'Fuchun Secondary School'},
 {'team_code': 'FHP', 'team_name': 'Fuhua Primary School'},
 {'team_code': 'GESP', 'team_name': 'Gan Eng Seng Primary School'},
 {'team_code': 'GES', 'team_name': 'Gan Eng Seng School'},
 {'team_code': 'GMSP', 'team_name': 'Geylang Methodist School (Primary)'},
 {'team_code': 'GMSS', 'team_name': 'Geylang Methodist Sec School'},
 {'team_code': 'GSP', 'team_name': 'Gongshang Primary School'},
 {'team_code': 'GDP', 'team_name': 'Greendale Primary School'},
 {'team_code': 'GRP', 'team_name': 'Greenridge Primary School'},
 {'team_code': 'GWP', 'team_name': 'Greenwood Primary School'},
 {'team_code': 'GYS', 'team_name': 'Guangyang Secondary School'},
 {'team_code': 'HSC', 'team_name': 'Hai Sing Catholic School'},
 {'team_code': 'HGS', 'team_name': "Haig Girls' School"},
 {'team_code': 'HSS', 'team_name': 'Henderson Sec Sch'},
 {'team_code': 'HPP', 'team_name': 'Henry Park Primary School'},
 {'team_code': 'HIP', 'team_name': "Holy Innocents' Primary School"},
 {'team_code': 'HKS', 'team_name': 'Hong Kah Sec School'},
 {'team_code': 'HWS', 'team_name': 'Hong Wen School'},
 {'team_code': 'HZP', 'team_name': 'Horizon Primary School'},
 {'team_code': 'HGP', 'team_name': 'Hougang Primary School'},
 {'team_code': 'HY', 'team_name': 'Hua Yi Sec Sch'},
 {'team_code': 'HMP', 'team_name': 'Huamin Primary School'},
 {'team_code': 'HCAA', 'team_name': 'Hwa Chong Alumni Association'},
 {'team_code': 'HCI', 'team_name': 'Hwa Chong Institution'},
 {'team_code': 'HCIC', 'team_name': 'Hwa Chong Institution College'},
 {'team_code': 'IJC', 'team_name': 'Innova Junior College'},
 {'team_code': 'IPS', 'team_name': 'Innova Primary School'},
 {'team_code': 'ITE', 'team_name': 'Institute of Tech Education'},
 {'team_code': 'IFS', 'team_name': 'International French School (Singapore) LTD'},
 {'team_code': 'JOA', 'team_name': 'Jacq Of All Trades'},
 {'team_code': 'JMP', 'team_name': 'Jiemin Primary School'},
 {'team_code': 'JSP', 'team_name': 'Jing Shan Primary School'},
 {'team_code': 'JAA', 'team_name': 'Johor Athletic Association'},
 {'team_code': 'JSA', 'team_name': 'JS Athletics'},
 {'team_code': 'JYP', 'team_name': 'Junyuan Primary School'},
 {'team_code': 'JY', 'team_name': 'Junyuan Secondary School'},
 {'team_code': 'JJC', 'team_name': 'Jurong Junior College'},
 {'team_code': 'JPS', 'team_name': 'Jurong Primary School'},
 {'team_code': 'JSS', 'team_name': 'Jurong Seconday School'},
 {'team_code': 'JWP', 'team_name': 'Jurong West Primary School'},
 {'team_code': 'KMP', 'team_name': 'Keming Primary School'},
 {'team_code': 'KRSS', 'team_name': 'Kent Ridge Secondary School'},
 {'team_code': 'KCS', 'team_name': 'Kheng Cheng School'},
 {'team_code': 'KHS', 'team_name': 'Kong Hwa School'},
 {'team_code': 'KJP', 'team_name': 'Kranji Primary School'},
 {'team_code': 'KCP', 'team_name': 'Kuo Chuan Presbyterian Primary School'},
 {'team_code': 'KCP', 'team_name': 'Kuo Chuan Presbyterian Sec Sch'},
 {'team_code': 'LB', 'team_name': 'Lacticbuds'},
 {'team_code': 'LSP', 'team_name': 'Lakeside Primary School'},
 {'team_code': 'LHP', 'team_name': 'Lianhua Primary School'},
 {'team_code': 'MS', 'team_name': 'Macpherson Secondary School'},
 {'team_code': 'MR25', 'team_name': 'Macritchie Runners 25'},
 {'team_code': 'MBS', 'team_name': 'Maha Bodhi School'},
 {'team_code': 'MSH', 'team_name': 'Maris Stella High School'},
 {'team_code': 'MSHP', 'team_name': 'Maris Stella High School (Primary)'},
 {'team_code': 'MAR', 'team_name': 'Marsiling Primary School'},
 {'team_code': 'MMC', 'team_name': 'Marymount Convent School'},
 {'team_code': 'MAXF', 'team_name': 'Maxform'},
 {'team_code': 'MFP', 'team_name': 'Mayflower Primary School'},
 {'team_code': 'MTS', 'team_name': 'Mee Toh School'},
 {'team_code': 'MRP', 'team_name': 'Meridian Primary School'},
 {'team_code': 'MGS', 'team_name': "Methodist Girls' School"},
 {'team_code': 'MGSP', 'team_name': "Methodist Girls' School (Primary)"},
 {'team_code': 'MI', 'team_name': 'Millennia Institute'},
 {'team_code': 'MFJ', 'team_name': 'Montfort Junior School'},
 {'team_code': 'MCA', 'team_name': 'My Coaching Academy'},
 {'team_code': 'NCHS', 'team_name': 'Nan Chiau High School'},
 {'team_code': 'NCP', 'team_name': 'Nan Chiau Primary School'},
 {'team_code': 'NHP', 'team_name': 'Nan Hua Primary School'},
 {'team_code': 'NYG', 'team_name': "Nanyang Girls' High School"},
 {'team_code': 'NYJC', 'team_name': 'Nanyang Junior College'},
 {'team_code': 'NYP', 'team_name': 'Nanyang Polytechnic'},
 {'team_code': 'NYPS', 'team_name': 'Nanyang Primary School'},
 {'team_code': 'NYP', 'team_name': 'Nanyang Primary School'},
 {'team_code': 'NTU', 'team_name': 'Nanyang Technological Uni'},
 {'team_code': 'NJC', 'team_name': 'National Junior College'},
 {'team_code': 'NUS', 'team_name': 'National University Singapore'},
 {'team_code': 'NBP', 'team_name': 'Naval Base Primary School'},
 {'team_code': 'NTP', 'team_name': 'New Town Primary School'},
 {'team_code': 'NP', 'team_name': 'Ngee Ann Polytechnic'},
 {'team_code': 'NAP', 'team_name': 'Ngee Ann Primary School'},
 {'team_code': 'NSP', 'team_name': 'North Spring Primary School'},
 {'team_code': 'NVP', 'team_name': 'North View Primary School'},
 {'team_code': 'NVIS', 'team_name': 'North Vista Primary School'},
 {'team_code': 'NV', 'team_name': 'North Vista Secondary School'},
 {'team_code': 'NLP', 'team_name': 'Northland Primary School'},
 {'team_code': 'NSS', 'team_name': 'Northland Secondary School'},
 {'team_code': 'NOP', 'team_name': 'Northoaks Primary School'},
 {'team_code': 'NSH', 'team_name': 'Northshore Primary School'},
 {'team_code': 'NUSH', 'team_name': 'Nus High School'},
 {'team_code': 'OAS', 'team_name': 'Oasis Primary School'},
 {'team_code': 'OA', 'team_name': 'Oldham Athletics'},
 {'team_code': 'OMS', 'team_name': 'ONE Management SG LLP'},
 {'team_code': 'OEP', 'team_name': 'Opera Estate Primary School'},
 {'team_code': 'OPSS', 'team_name': 'Orchid Park Secondary School'},
 {'team_code': 'PLV', 'team_name': 'Palm View Primary School'},
 {'team_code': 'PKV', 'team_name': 'Park View Primary School'},
 {'team_code': 'PRP', 'team_name': 'Pasir Ris Primary School'},
 {'team_code': 'PRSS', 'team_name': 'Pasir Ris Sec'},
 {'team_code': 'PLMGS', 'team_name': "Paya Lebar Methodist Girls'"},
 {'team_code': 'PLMGP', 'team_name': "Paya Lebar Methodist Girls' School (Primary)"},
 {'team_code': 'PCP', 'team_name': 'Pei Chun Public School'},
 {'team_code': 'PHP', 'team_name': 'Pei Hwa Presbyterian Primary School'},
 {'team_code': 'PTP', 'team_name': 'Pei Tong Primary School'},
 {'team_code': 'PSS', 'team_name': 'Peirce Secondary School'},
 {'team_code': 'PYP', 'team_name': 'Peiying Primary School'},
 {'team_code': 'PJC', 'team_name': 'Pioneer Junior College'},
 {'team_code': 'PNP', 'team_name': 'Pioneer Primary School'},
 {'team_code': 'PCS', 'team_name': 'Poi Ching School'},
 {'team_code': 'PSA', 'team_name': 'Police Sports Association'},
 {'team_code': 'PEP', 'team_name': 'Princess Elizabeth Primary School'},
 {'team_code': 'PSRC', 'team_name': 'Prison Sports& Recreation Club'},
 {'team_code': 'PGC', 'team_name': 'Punggol Cove Primary School'},
 {'team_code': 'PGG', 'team_name': 'Punggol Green Primary School'},
 {'team_code': 'PGP', 'team_name': 'Punggol Primary School'},
 {'team_code': 'PGV', 'team_name': 'Punggol View Primary School'},
 {'team_code': 'QFP', 'team_name': 'Qifa Primary School'},
 {'team_code': 'QHP', 'team_name': 'Qihua Primary School'},
 {'team_code': 'QPS', 'team_name': 'Queenstown Primary School'},
 {'team_code': 'QSS', 'team_name': 'Queensway Secondary School'},
 {'team_code': 'RMP', 'team_name': 'Radin Mas Primary School'},
 {'team_code': 'RGP', 'team_name': "Raffles Girls' Primary School"},
 {'team_code': 'RGS', 'team_name': "Raffles Girls' School"},
 {'team_code': 'RI', 'team_name': 'Raffles Institution'},
 {'team_code': 'RIJC', 'team_name': 'Raffles Institution JC'},
 {'team_code': 'REAC', 'team_name': 'Reactiv'},
 {'team_code': 'RHSC', 'team_name': 'Red Hawk Sports Club'},
 {'team_code': 'RSS', 'team_name': 'Red Swastika School'},
 {'team_code': 'RGT', 'team_name': 'Regent Secondary School'},
 {'team_code': 'RTC', 'team_name': 'Regional Training Centre'},
 {'team_code': 'RP', 'team_name': 'Republic Polytechnic'},
 {'team_code': 'RVH', 'team_name': 'River Valley High School'},
 {'team_code': 'RVP', 'team_name': 'River Valley Primary School'},
 {'team_code': 'RSP', 'team_name': 'Riverside Primary School'},
 {'team_code': 'RSS', 'team_name': 'Riverside Secondary School'},
 {'team_code': 'RIV', 'team_name': 'Rivervale Primary School'},
 {'team_code': 'ROS', 'team_name': 'Rosyth School'},
 {'team_code': 'RPS', 'team_name': 'Rulang Primary School'},
 {'team_code': 'SAG', 'team_name': 'Saga Athletics'},
 {'team_code': 'SBP', 'team_name': 'Sembawang Primary School'},
 {'team_code': 'SKP', 'team_name': 'Seng Kang Primary School'},
 {'team_code': 'SKS', 'team_name': 'Seng Kang Secondary School'},
 {'team_code': 'SKG', 'team_name': 'Sengkang Green Primary School'},
 {'team_code': 'SRJC', 'team_name': 'Serangoon Junior College'},
 {'team_code': 'SDSC', 'team_name': 'SG Disability Sports Council'},
 {'team_code': 'SQP', 'team_name': 'Shuqun Primary School'},
 {'team_code': 'SLP', 'team_name': 'Si Ling Primary School'},
 {'team_code': 'SIA', 'team_name': 'SIA Group Sports Club'},
 {'team_code': 'SSS', 'team_name': 'Siglap Secondary School'},
 {'team_code': 'SGP', 'team_name': 'Singapore'},
 {'team_code': 'SCGP', 'team_name': "Singapore Chinese Girls' Primary School"},
 {'team_code': 'SCGS', 'team_name': "Singapore Chinese Girls' School"},
 {'team_code': 'SFR', 'team_name': 'Singapore Falcons Running Club'},
 {'team_code': 'SIM', 'team_name': 'Singapore Institute of Managem'},
 {'team_code': 'SIT', 'team_name': 'Singapore Institute of Technology'},
 {'team_code': 'SMU', 'team_name': 'Singapore Management University'},
 {'team_code': 'SMA', 'team_name': 'Singapore Masters Athletics'},
 {'team_code': 'SMTF', 'team_name': 'Singapore Masters Track & Field Association'},
 {'team_code': 'SP', 'team_name': 'Singapore Polytechnic'},
 {'team_code': 'SSSC', 'team_name': 'Singapore Schools Sports Council'},
 {'team_code': 'SSP', 'team_name': 'Singapore Sports School'},
 {'team_code': 'SSH', 'team_name': 'Singapore Shufflers'},
 {'team_code': 'SST', 'team_name': 'School of Science and Technology'},
 {'team_code': 'SUA', 'team_name': 'Singapore Ultrarunners Association'},
 {'team_code': 'SGU', 'team_name': 'Singapore University'},
 {'team_code': 'SUSS', 'team_name': 'Singapore University of Social Sciences'},
 {'team_code': 'SUTD', 'team_name': 'Singapore University of Technology and Design'},
 {'team_code': 'SKY', 'team_name': 'Sky Athletics'},
 {'team_code': 'SVP', 'team_name': 'South View Primary School'},
 {'team_code': 'SOS', 'team_name': 'Special Olympic Singapore'},
 {'team_code': 'SDP', 'team_name': 'Springdale Primary School'},
 {'team_code': 'SAJC', 'team_name': "St Andrew's Junior College"},
 {'team_code': 'SAC', 'team_name': "St Anthony's Canossian Secondary School"},
 {'team_code': 'SJI', 'team_name': "St Joseph's Institution"},
 {'team_code': 'SAJ', 'team_name': "St. Andrew's Junior School"},
 {'team_code': 'SAS', 'team_name': "St. Andrew's Secondary School"},
 {'team_code': 'SACP', 'team_name': "St. Anthony's Canossian Primary School"},
 {'team_code': 'SAP', 'team_name': "St. Anthony's Primary School"},
 {'team_code': 'SGP', 'team_name': "St. Gabriel's Primary School"},
 {'team_code': 'SHP', 'team_name': "St. Hilda's Primary School"},
 {'team_code': 'SJIJ', 'team_name': "St. Joseph's Institution Junior"},
 {'team_code': 'SMP', 'team_name': "St. Margaret's School (Primary)"},
 {'team_code': 'SPS', 'team_name': "St. Patrick's School"},
 {'team_code': 'STS', 'team_name': "St. Stephen's School"},
 {'team_code': 'SWIF', 'team_name': 'Swift Athletes Association'},
 {'team_code': 'TPJC', 'team_name': 'Tampines Junior College'},
 {'team_code': 'TMJC', 'team_name': 'Tampines Meridian Junior College'},
 {'team_code': 'TNP', 'team_name': 'Tampines North Primary School'},
 {'team_code': 'TPP', 'team_name': 'Tampines Primary School'},
 {'team_code': 'TLSS', 'team_name': 'Tanglin Secondary School'},
 {'team_code': 'TSS', 'team_name': 'Tanglin Secondary School'},
 {'team_code': 'TTS', 'team_name': 'Tanglin Trust School'},
 {'team_code': 'TJKP', 'team_name': 'Tanjong Katong Primary School'},
 {'team_code': 'TK', 'team_name': 'Tanjong Katong Secondary Sch'},
 {'team_code': 'TNS', 'team_name': 'Tao Nan School'},
 {'team_code': 'TCT', 'team_name': 'Team Cicada Trackers'},
 {'team_code': 'TS', 'team_name': 'Team Start Singapore'},
 {'team_code': 'TF', 'team_name': 'TeamFabian'},
 {'team_code': 'TGP', 'team_name': 'Teck Ghee Primary School'},
 {'team_code': 'TWP', 'team_name': 'Teck Whye Primary School'},
 {'team_code': 'TKP', 'team_name': 'Telok Kurau Primary School'},
 {'team_code': 'TJC', 'team_name': 'Temasek Junior College'},
 {'team_code': 'TMP', 'team_name': 'Temasek Polytechnic'},
 {'team_code': 'TP', 'team_name': 'Temasek Polytechnic'},
 {'team_code': 'TPS', 'team_name': 'Temasek Primary School'},
 {'team_code': 'TMP', 'team_name': 'Temasek Primary School'},
 {'team_code': 'TMS', 'team_name': 'Temasek Secondary School'},
 {'team_code': 'TKSP', 'team_name': 'Total Kinetics Sports Pte Ltd'},
 {'team_code': 'T360', 'team_name': 'Totality 360'},
 {'team_code': 'TVP', 'team_name': 'Townsville Primary School'},
 {'team_code': 'TRSA', 'team_name': 'Trackstar Athletics'},
 {'team_code': 'UPS', 'team_name': 'Unity Primary School'},
 {'team_code': 'VPS', 'team_name': 'Valour Primary School'},
 {'team_code': 'VRV', 'team_name': 'Verve Fitness'},
 {'team_code': 'VJC', 'team_name': 'Victoria Junior College'},
 {'team_code': 'VS', 'team_name': 'Victoria School'},
 {'team_code': 'WAT', 'team_name': 'Waterway Primary School'},
 {'team_code': 'WTP', 'team_name': 'Wellington Primary School'},
 {'team_code': 'WGP', 'team_name': 'West Grove Primary School'},
 {'team_code': 'WSPR', 'team_name': 'West Spring Primary School'},
 {'team_code': 'WSS', 'team_name': 'West Spring Secondary School'},
 {'team_code': 'WVP', 'team_name': 'West View Primary School'},
 {'team_code': 'WWP', 'team_name': 'Westwood Primary School'},
 {'team_code': 'WSP', 'team_name': 'White Sands Primary School'},
 {'team_code': 'WAC', 'team_name': 'Wings Athletics Club'},
 {'team_code': 'WDG', 'team_name': 'Woodgrove Primary School'},
 {'team_code': 'WDP', 'team_name': 'Woodlands Primary School'},
 {'team_code': 'WDR', 'team_name': 'Woodlands Ring Primary School'},
 {'team_code': 'WDL', 'team_name': 'Woodlands Secondary School'},
 {'team_code': 'XHP', 'team_name': 'Xinghua Primary School'},
 {'team_code': 'XNP', 'team_name': 'Xingnan Primary School'},
 {'team_code': 'XMP', 'team_name': 'Xinmin Primary School'},
 {'team_code': 'XSP', 'team_name': 'Xishan Primary School'},
 {'team_code': 'YZP', 'team_name': 'Yangzheng Primary School'},
 {'team_code': 'YTP', 'team_name': 'Yew Tee Primary School'},
 {'team_code': 'YCK', 'team_name': 'Yio Chu Kang Primary School'},
 {'team_code': 'YJC', 'team_name': 'Yishun Junior College'},
 {'team_code': 'YIS', 'team_name': 'Yishun Primary School'},
 {'team_code': 'YTSS', 'team_name': 'Yishun Town Secondary School'},
 {'team_code': 'YNP', 'team_name': 'Yu Neng Primary School'},
 {'team_code': 'YCS', 'team_name': 'Yuan Ching Secondary School'},
 {'team_code': 'YHP', 'team_name': 'Yuhua Primary School'},
 {'team_code': 'YMP', 'team_name': 'Yumin Primary School'},
 {'team_code': 'ZDP', 'team_name': 'Zhangde Primary School'},
 {'team_code': 'ZHP', 'team_name': 'Zhenghua Primary School'},
 {'team_code': 'ZHO', 'team_name': 'Zhonghua Primary School'}]
TEAM_CODES = ['ACSB',
 'AAC',
 'ADP',
 'ADSS',
 'AIC',
 'AIP',
 'AIS',
 'ATS',
 'ALP',
 'AGP',
 'AJC',
 'APS',
 'ASGC',
 'AMK',
 'AMKS',
 'ACJC',
 'ACSI',
 'ACST',
 'ACSJ',
 'ACSP',
 'ANG',
 'BEA',
 'BTY',
 'BGP',
 'BG',
 'BV',
 'BDM',
 'BS',
 'BPSS',
 'BRP',
 'BLG',
 'BPJ',
 'BTP',
 'BTV',
 'CPS',
 'CCP',
 'CAN',
 'CASU',
 'CH',
 'CHSP',
 'CJC',
 'CG',
 'CDP',
 'CCS',
 'CKP',
 'CDS',
 'KTC',
 'IJK',
 'KC',
 'OLGC',
 'OLN',
 'OLQP',
 'IJP',
 'HIJ',
 'STC',
 'SNG',
 'SNGP',
 'CFS',
 'CZP',
 'CHR',
 'CCKP',
 'CCK',
 'CCHM',
 'CTP',
 'ZOOM',
 'CWSS',
 'CVP',
 'CCP',
 'COR',
 'CAA',
 'CGS',
 'CRS',
 'DMP',
 'DZP',
 'DLS',
 'DYSS',
 'DUC',
 'DHS',
 'ESP',
 'EFP',
 'EPP',
 'ENDP',
 'EC',
 'EGS',
 'EVGP',
 'EJC',
 'FTS',
 'FAC',
 'FMP',
 'FPP',
 'FSP',
 'FVP',
 'FTP',
 'FTA',
 'FRP',
 'FCP',
 'FC',
 'FHP',
 'GESP',
 'GES',
 'GMSP',
 'GMSS',
 'GSP',
 'GDP',
 'GRP',
 'GWP',
 'GYS',
 'HSC',
 'HGS',
 'HSS',
 'HPP',
 'HIP',
 'HKS',
 'HWS',
 'HZP',
 'HGP',
 'HY',
 'HMP',
 'HCAA',
 'HCI',
 'HCIC',
 'IJC',
 'IPS',
 'ITE',
 'IFS',
 'JOA',
 'JMP',
 'JSP',
 'JAA',
 'JSA',
 'JYP',
 'JY',
 'JJC',
 'JPS',
 'JSS',
 'JWP',
 'KMP',
 'KRSS',
 'KCS',
 'KHS',
 'KJP',
 'KCP',
 'KCP',
 'LB',
 'LSP',
 'LHP',
 'MS',
 'MR25',
 'MBS',
 'MSH',
 'MSHP',
 'MAR',
 'MMC',
 'MAXF',
 'MFP',
 'MTS',
 'MRP',
 'MGS',
 'MGSP',
 'MI',
 'MFJ',
 'MCA',
 'NCHS',
 'NCP',
 'NHP',
 'NYG',
 'NYJC',
 'NYP',
 'NYPS',
 'NYP',
 'NTU',
 'NJC',
 'NUS',
 'NBP',
 'NTP',
 'NP',
 'NAP',
 'NSP',
 'NVP',
 'NVIS',
 'NV',
 'NLP',
 'NSS',
 'NOP',
 'NSH',
 'NUSH',
 'OAS',
 'OA',
 'OMS',
 'OEP',
 'OPSS',
 'PLV',
 'PKV',
 'PRP',
 'PRSS',
 'PLMGS',
 'PLMGP',
 'PCP',
 'PHP',
 'PTP',
 'PSS',
 'PYP',
 'PJC',
 'PNP',
 'PCS',
 'PSA',
 'PEP',
 'PSRC',
 'PGC',
 'PGG',
 'PGP',
 'PGV',
 'QFP',
 'QHP',
 'QPS',
 'QSS',
 'RMP',
 'RGP',
 'RGS',
 'RI',
 'RIJC',
 'REAC',
 'RHSC',
 'RSS',
 'RGT',
 'RTC',
 'RP',
 'RVH',
 'RVP',
 'RSP',
 'RSS',
 'RIV',
 'ROS',
 'RPS',
 'SAG',
 'SBP',
 'SKP',
 'SKS',
 'SKG',
 'SRJC',
 'SDSC',
 'SQP',
 'SLP',
 'SIA',
 'SSS',
 'SGP',
 'SCGP',
 'SCGS',
 'SFR',
 'SIM',
 'SIT',
 'SMU',
 'SMA',
 'SMTF',
 'SP',
 'SSSC',
 'SSP',
 'SSH',
 'SST',
 'SUA',
 'SGU',
 'SUSS',
 'SUTD',
 'SKY',
 'SVP',
 'SOS',
 'SDP',
 'SAJC',
 'SAC',
 'SJI',
 'SAJ',
 'SAS',
 'SACP',
 'SAP',
 'SGP',
 'SHP',
 'SJIJ',
 'SMP',
 'SPS',
 'STS',
 'SWIF',
 'TPJC',
 'TMJC',
 'TNP',
 'TPP',
 'TLSS',
 'TSS',
 'TTS',
 'TJKP',
 'TK',
 'TNS',
 'TCT',
 'TS',
 'TF',
 'TGP',
 'TWP',
 'TKP',
 'TJC',
 'TMP',
 'TP',
 'TPS',
 'TMP',
 'TMS',
 'TKSP',
 'T360',
 'TVP',
 'TRSA',
 'UPS',
 'VPS',
 'VRV',
 'VJC',
 'VS',
 'WAT',
 'WTP',
 'WGP',
 'WSPR',
 'WSS',
 'WVP',
 'WWP',
 'WSP',
 'WAC',
 'WDG',
 'WDP',
 'WDR',
 'WDL',
 'XHP',
 'XNP',
 'XMP',
 'XSP',
 'YZP',
 'YTP',
 'YCK',
 'YJC',
 'YIS',
 'YTSS',
 'YNP',
 'YCS',
 'YHP',
 'YMP',
 'ZDP',
 'ZHP',
 'ZHO']
TEAM_CODE_TO_NAME = {'AAC': 'ActiveSG Academies & Club',
 'ACJC': 'Anglo Chinese Junior College',
 'ACSB': 'ACS Barker',
 'ACSI': 'Anglo‑Chinese School (Indep)',
 'ACSJ': 'Anglo-Chinese School (Junior)',
 'ACSP': 'Anglo-Chinese School (Primary)',
 'ACST': 'Anglo‑Chinese School (International)',
 'ADP': 'Admiralty Primary School',
 'ADSS': 'Admiralty Secondary School',
 'AGP': 'Anchor Green Primary School',
 'AIC': 'Asian Inter-Clubs Athletics Alliance Singapore',
 'AIP': 'Ahmad Ibrahim Primary School',
 'AIS': 'Ahmad Ibrahim Secondary School',
 'AJC': 'Anderson JC',
 'ALP': 'Alexandra Primary School',
 'AMK': 'Ang Mo Kio Primary School',
 'AMKS': 'Ang Mo Kio Secondary School',
 'ANG': 'Angsana Primary School',
 'APS': 'Anderson Primary School',
 'ASGC': 'Anderson Secondary School',
 'ATS': 'Ai Tong School',
 'BDM': 'Bendemeer Primary School',
 'BEA': 'Beacon Primary School',
 'BG': 'Bedok Green Secondary School',
 'BGP': 'Bedok Green Primary School',
 'BLG': 'Boon Lay Garden Primary School',
 'BPJ': 'Bukit Panjang Primary School',
 'BPSS': 'Bishan Park Secondary School',
 'BRP': 'Blangah Rise Primary School',
 'BS': 'Bendemeer Secondary School',
 'BTP': 'Bukit Timah Primary School',
 'BTV': 'Bukit View Primary School',
 'BTY': 'Beatty Secondary School',
 'BV': 'Bedok View Sec School',
 'CAA': 'Cougar Athletic Association',
 'CAN': 'Cantonment Primary School',
 'CASU': 'Casuarina Primary School',
 'CCHM': 'Chung Cheng High School (Main)',
 'CCK': 'Chua Chu Kang Secondary School',
 'CCKP': 'Chua Chu Kang Primary School',
 'CCP': 'Concord Primary School',
 'CCS': 'Changkat Changi Secondary Sch',
 'CDP': 'Cedar Primary School',
 'CDS': 'Chestnut Drive Sec Sch',
 'CFS': 'Chongfu School',
 'CG': 'Cedar Girls Secondary School',
 'CGS': "Crescent Girls' School",
 'CH': 'Catholic High School',
 'CHR': 'Christ Church Secondary School',
 'CHSP': 'Catholic High School (Primary)',
 'CJC': 'Catholic Junior College',
 'CKP': 'Changkat Primary School',
 'COR': 'Corporation Primary School',
 'CPS': 'Canberra Primary School',
 'CRS': 'Crest Secondary School',
 'CTP': 'Clementi Primary School',
 'CVP': 'Compassvale Primary School',
 'CWSS': 'Commonwealth Sec Sch',
 'CZP': 'Chongzheng Primary School',
 'DHS': 'Dunman High School',
 'DLS': 'De La Salle School',
 'DMP': 'Damai Primary School',
 'DUC': 'Dulwich College',
 'DYSS': 'Deyi Secondary School',
 'DZP': 'Dazhong Primary School',
 'EC': 'Erovra Club',
 'EFP': 'Edgefield Primary School',
 'EGS': 'Eunoia Junior College',
 'EJC': 'Evergreen Secondary School',
 'ENDP': 'Endeavour Primary School',
 'EPP': 'Elias Park Primary School',
 'ESP': 'East Spring Primary School',
 'EVGP': 'Evergreen Primary School',
 'FAC': 'Flash Athletic Club',
 'FC': 'Fuchun Secondary School',
 'FCP': 'Fuchun Primary School',
 'FHP': 'Fuhua Primary School',
 'FMP': 'Fairfield Methodist School (Primary)',
 'FPP': 'Farrer Park Primary School',
 'FRP': 'Frontier Primary School',
 'FSP': 'Fengshan Primary School',
 'FTA': 'Fortius Athletics',
 'FTP': 'First Toa Payoh Primary School',
 'FTS': 'Fast Track Sports',
 'FVP': 'Fernvale Primary School',
 'GDP': 'Greendale Primary School',
 'GES': 'Gan Eng Seng School',
 'GESP': 'Gan Eng Seng Primary School',
 'GMSP': 'Geylang Methodist School (Primary)',
 'GMSS': 'Geylang Methodist Sec School',
 'GRP': 'Greenridge Primary School',
 'GSP': 'Gongshang Primary School',
 'GWP': 'Greenwood Primary School',
 'GYS': 'Guangyang Secondary School',
 'HCAA': 'Hwa Chong Alumni Association',
 'HCI': 'Hwa Chong Institution',
 'HCIC': 'Hwa Chong Institution College',
 'HGP': 'Hougang Primary School',
 'HGS': "Haig Girls' School",
 'HIJ': 'Chij Secondary (Toa Payoh)',
 'HIP': "Holy Innocents' Primary School",
 'HKS': 'Hong Kah Sec School',
 'HMP': 'Huamin Primary School',
 'HPP': 'Henry Park Primary School',
 'HSC': 'Hai Sing Catholic School',
 'HSS': 'Henderson Sec Sch',
 'HWS': 'Hong Wen School',
 'HY': 'Hua Yi Sec Sch',
 'HZP': 'Horizon Primary School',
 'IFS': 'International French School (Singapore) LTD',
 'IJC': 'Innova Junior College',
 'IJK': 'CHIJ (Kellock)',
 'IJP': 'CHIJ Primary (Toa Payoh)',
 'IPS': 'Innova Primary School',
 'ITE': 'Institute of Tech Education',
 'JAA': 'Johor Athletic Association',
 'JJC': 'Jurong Junior College',
 'JMP': 'Jiemin Primary School',
 'JOA': 'Jacq Of All Trades',
 'JPS': 'Jurong Primary School',
 'JSA': 'JS Athletics',
 'JSP': 'Jing Shan Primary School',
 'JSS': 'Jurong Seconday School',
 'JWP': 'Jurong West Primary School',
 'JY': 'Junyuan Secondary School',
 'JYP': 'Junyuan Primary School',
 'KC': 'Chij Katong Convent',
 'KCP': 'Kuo Chuan Presbyterian Sec Sch',
 'KCS': 'Kheng Cheng School',
 'KHS': 'Kong Hwa School',
 'KJP': 'Kranji Primary School',
 'KMP': 'Keming Primary School',
 'KRSS': 'Kent Ridge Secondary School',
 'KTC': 'CHIJ (Katong) Primary',
 'LB': 'Lacticbuds',
 'LHP': 'Lianhua Primary School',
 'LSP': 'Lakeside Primary School',
 'MAR': 'Marsiling Primary School',
 'MAXF': 'Maxform',
 'MBS': 'Maha Bodhi School',
 'MCA': 'My Coaching Academy',
 'MFJ': 'Montfort Junior School',
 'MFP': 'Mayflower Primary School',
 'MGS': "Methodist Girls' School",
 'MGSP': "Methodist Girls' School (Primary)",
 'MI': 'Millennia Institute',
 'MMC': 'Marymount Convent School',
 'MR25': 'Macritchie Runners 25',
 'MRP': 'Meridian Primary School',
 'MS': 'Macpherson Secondary School',
 'MSH': 'Maris Stella High School',
 'MSHP': 'Maris Stella High School (Primary)',
 'MTS': 'Mee Toh School',
 'NAP': 'Ngee Ann Primary School',
 'NBP': 'Naval Base Primary School',
 'NCHS': 'Nan Chiau High School',
 'NCP': 'Nan Chiau Primary School',
 'NHP': 'Nan Hua Primary School',
 'NJC': 'National Junior College',
 'NLP': 'Northland Primary School',
 'NOP': 'Northoaks Primary School',
 'NP': 'Ngee Ann Polytechnic',
 'NSH': 'Northshore Primary School',
 'NSP': 'North Spring Primary School',
 'NSS': 'Northland Secondary School',
 'NTP': 'New Town Primary School',
 'NTU': 'Nanyang Technological Uni',
 'NUS': 'National University Singapore',
 'NUSH': 'Nus High School',
 'NV': 'North Vista Secondary School',
 'NVIS': 'North Vista Primary School',
 'NVP': 'North View Primary School',
 'NYG': "Nanyang Girls' High School",
 'NYJC': 'Nanyang Junior College',
 'NYP': 'Nanyang Primary School',
 'NYPS': 'Nanyang Primary School',
 'OA': 'Oldham Athletics',
 'OAS': 'Oasis Primary School',
 'OEP': 'Opera Estate Primary School',
 'OLGC': 'CHIJ Our Lady of Good Counsel',
 'OLN': 'CHIJ Our Lady of the Nativity',
 'OLQP': 'CHIJ Our Lady Queen of Peace',
 'OMS': 'ONE Management SG LLP',
 'OPSS': 'Orchid Park Secondary School',
 'PCP': 'Pei Chun Public School',
 'PCS': 'Poi Ching School',
 'PEP': 'Princess Elizabeth Primary School',
 'PGC': 'Punggol Cove Primary School',
 'PGG': 'Punggol Green Primary School',
 'PGP': 'Punggol Primary School',
 'PGV': 'Punggol View Primary School',
 'PHP': 'Pei Hwa Presbyterian Primary School',
 'PJC': 'Pioneer Junior College',
 'PKV': 'Park View Primary School',
 'PLMGP': "Paya Lebar Methodist Girls' School (Primary)",
 'PLMGS': "Paya Lebar Methodist Girls'",
 'PLV': 'Palm View Primary School',
 'PNP': 'Pioneer Primary School',
 'PRP': 'Pasir Ris Primary School',
 'PRSS': 'Pasir Ris Sec',
 'PSA': 'Police Sports Association',
 'PSRC': 'Prison Sports& Recreation Club',
 'PSS': 'Peirce Secondary School',
 'PTP': 'Pei Tong Primary School',
 'PYP': 'Peiying Primary School',
 'QFP': 'Qifa Primary School',
 'QHP': 'Qihua Primary School',
 'QPS': 'Queenstown Primary School',
 'QSS': 'Queensway Secondary School',
 'REAC': 'Reactiv',
 'RGP': "Raffles Girls' Primary School",
 'RGS': "Raffles Girls' School",
 'RGT': 'Regent Secondary School',
 'RHSC': 'Red Hawk Sports Club',
 'RI': 'Raffles Institution',
 'RIJC': 'Raffles Institution JC',
 'RIV': 'Rivervale Primary School',
 'RMP': 'Radin Mas Primary School',
 'ROS': 'Rosyth School',
 'RP': 'Republic Polytechnic',
 'RPS': 'Rulang Primary School',
 'RSP': 'Riverside Primary School',
 'RSS': 'Riverside Secondary School',
 'RTC': 'Regional Training Centre',
 'RVH': 'River Valley High School',
 'RVP': 'River Valley Primary School',
 'SAC': "St Anthony's Canossian Secondary School",
 'SACP': "St. Anthony's Canossian Primary School",
 'SAG': 'Saga Athletics',
 'SAJ': "St. Andrew's Junior School",
 'SAJC': "St Andrew's Junior College",
 'SAP': "St. Anthony's Primary School",
 'SAS': "St. Andrew's Secondary School",
 'SBP': 'Sembawang Primary School',
 'SCGP': "Singapore Chinese Girls' Primary School",
 'SCGS': "Singapore Chinese Girls' School",
 'SDP': 'Springdale Primary School',
 'SDSC': 'SG Disability Sports Council',
 'SFR': 'Singapore Falcons Running Club',
 'SGP': "St. Gabriel's Primary School",
 'SGU': 'Singapore University',
 'SHP': "St. Hilda's Primary School",
 'SIA': 'SIA Group Sports Club',
 'SIM': 'Singapore Institute of Managem',
 'SIT': 'Singapore Institute of Technology',
 'SJI': "St Joseph's Institution",
 'SJIJ': "St. Joseph's Institution Junior",
 'SKG': 'Sengkang Green Primary School',
 'SKP': 'Seng Kang Primary School',
 'SKS': 'Seng Kang Secondary School',
 'SKY': 'Sky Athletics',
 'SLP': 'Si Ling Primary School',
 'SMA': 'Singapore Masters Athletics',
 'SMP': "St. Margaret's School (Primary)",
 'SMTF': 'Singapore Masters Track & Field Association',
 'SMU': 'Singapore Management University',
 'SNG': "Chij St. Nicholas Girls'",
 'SNGP': "CHIJ St. Nicholas Girls' School (Primary)",
 'SOS': 'Special Olympic Singapore',
 'SP': 'Singapore Polytechnic',
 'SPS': "St. Patrick's School",
 'SQP': 'Shuqun Primary School',
 'SRJC': 'Serangoon Junior College',
 'SSH': 'Singapore Shufflers',
 'SSP': 'Singapore Sports School',
 'SSS': 'Siglap Secondary School',
 'SSSC': 'Singapore Schools Sports Council',
 'SST': 'School of Science and Technology',
 'STC': "Chij St Theresa's Convent",
 'STS': "St. Stephen's School",
 'SUA': 'Singapore Ultrarunners Association',
 'SUSS': 'Singapore University of Social Sciences',
 'SUTD': 'Singapore University of Technology and Design',
 'SVP': 'South View Primary School',
 'SWIF': 'Swift Athletes Association',
 'T360': 'Totality 360',
 'TCT': 'Team Cicada Trackers',
 'TF': 'TeamFabian',
 'TGP': 'Teck Ghee Primary School',
 'TJC': 'Temasek Junior College',
 'TJKP': 'Tanjong Katong Primary School',
 'TK': 'Tanjong Katong Secondary Sch',
 'TKP': 'Telok Kurau Primary School',
 'TKSP': 'Total Kinetics Sports Pte Ltd',
 'TLSS': 'Tanglin Secondary School',
 'TMJC': 'Tampines Meridian Junior College',
 'TMP': 'Temasek Primary School',
 'TMS': 'Temasek Secondary School',
 'TNP': 'Tampines North Primary School',
 'TNS': 'Tao Nan School',
 'TP': 'Temasek Polytechnic',
 'TPJC': 'Tampines Junior College',
 'TPP': 'Tampines Primary School',
 'TPS': 'Temasek Primary School',
 'TRSA': 'Trackstar Athletics',
 'TS': 'Team Start Singapore',
 'TSS': 'Tanglin Secondary School',
 'TTS': 'Tanglin Trust School',
 'TVP': 'Townsville Primary School',
 'TWP': 'Teck Whye Primary School',
 'UPS': 'Unity Primary School',
 'VJC': 'Victoria Junior College',
 'VPS': 'Valour Primary School',
 'VRV': 'Verve Fitness',
 'VS': 'Victoria School',
 'WAC': 'Wings Athletics Club',
 'WAT': 'Waterway Primary School',
 'WDG': 'Woodgrove Primary School',
 'WDL': 'Woodlands Secondary School',
 'WDP': 'Woodlands Primary School',
 'WDR': 'Woodlands Ring Primary School',
 'WGP': 'West Grove Primary School',
 'WSP': 'White Sands Primary School',
 'WSPR': 'West Spring Primary School',
 'WSS': 'West Spring Secondary School',
 'WTP': 'Wellington Primary School',
 'WVP': 'West View Primary School',
 'WWP': 'Westwood Primary School',
 'XHP': 'Xinghua Primary School',
 'XMP': 'Xinmin Primary School',
 'XNP': 'Xingnan Primary School',
 'XSP': 'Xishan Primary School',
 'YCK': 'Yio Chu Kang Primary School',
 'YCS': 'Yuan Ching Secondary School',
 'YHP': 'Yuhua Primary School',
 'YIS': 'Yishun Primary School',
 'YJC': 'Yishun Junior College',
 'YMP': 'Yumin Primary School',
 'YNP': 'Yu Neng Primary School',
 'YTP': 'Yew Tee Primary School',
 'YTSS': 'Yishun Town Secondary School',
 'YZP': 'Yangzheng Primary School',
 'ZDP': 'Zhangde Primary School',
 'ZHO': 'Zhonghua Primary School',
 'ZHP': 'Zhenghua Primary School',
 'ZOOM': 'Club Zoom'}

# Nationality / country dropdown
COUNTRIES = ['Singapore',
 'Brunei',
 'Cambodia',
 'Malaysia',
 'Myanmar',
 'Laos',
 'Indonesia',
 'Philippines',
 'Thailand',
 'Timor Leste',
 'Vietnam',
 'China',
 'Japan',
 'South Korea',
 'North Korea',
 'Hong Kong',
 'Mongolia',
 'Afghanistan',
 'Netherlands Antilles',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua & Barbuda',
 'Australasia',
 'Argentina',
 'Armenia',
 'Aruba',
 'American Samoa',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bangladesh',
 'Barbados',
 'Burundi',
 'Belgium',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bosnia-Herzegovina',
 'Belize',
 'Belarus',
 'Bohemia',
 'Bolivia',
 'Botswana',
 'Brazil',
 'Bahrain',
 'Bulgaria',
 'Burkina Faso',
 'West Indies Federation',
 'Central African Republic',
 'Canada',
 'Cayman Islands',
 'Congo-Brazzaville',
 'Chad',
 'Chile',
 "Cote d'Ivoire",
 'Cameroon',
 'Democratic Republic of the Congo',
 'Cook Islands',
 'Colombia',
 'Comoros',
 'Cape Verde',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'Eritrea',
 'El Salvador',
 'Spain',
 'Estonia',
 'Ethiopia',
 'Unified Team',
 'Fiji',
 'Finland',
 'France',
 'West Germany',
 'Federal States of Micronesia',
 'Gabon',
 'Gambia',
 'Great Britain',
 'Guinea Bissau',
 'German Democratic Republic',
 'Georgia',
 'Equatorial Guinea',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guam',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'India',
 'Independent Olympic Athletes',
 'Iran',
 'Ireland',
 'Iraq',
 'Iceland',
 'Israel',
 'Virgin Islands',
 'Italy',
 'British Virgin Islands',
 'Jamaica',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kyrgyzstan',
 'Kiribati',
 'Kosovo',
 'Saudi Arabia',
 'Kuwait',
 'Latvia',
 'Libya',
 'Liberia',
 'Saint Lucia',
 'Lesotho',
 'Lebanon',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Madagascar',
 'Morocco',
 'Malawi',
 'Moldova',
 'Maldives',
 'Mexico',
 'Marshall Islands',
 'Macedonia',
 'Mali',
 'Malta',
 'Montenegro',
 'Monaco',
 'Mozambique',
 'Mauritius',
 'Mauritania',
 'Namibia',
 'North Borneo',
 'Nicaragua',
 'Netherlands',
 'Nepal',
 'Nigeria',
 'Niger',
 'Norway',
 'Nauru',
 'New Zealand',
 'Oman',
 'Pakistan',
 'Panama',
 'Paraguay',
 'Peru',
 'Palestine',
 'Palau',
 'Papua New Guinea',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Team of Refugee Olympic Athletes',
 'Romania',
 'South Africa',
 'Russia',
 'Rwanda',
 'Saar',
 'Samoa',
 'Serbia and Montenegro',
 'Senegal',
 'Seychelles',
 'Saint Kitts and Nevis',
 'Sierra Leone',
 'Slovenia',
 'San Marino',
 'Solomon Islands',
 'Somalia',
 'Serbia',
 'Sri Lanka',
 'South Sudan',
 'Sao Tome and Principe',
 'Sudan',
 'Switzerland',
 'Suriname',
 'Slovakia',
 'Sweden',
 'Swaziland',
 'Syria',
 'Tanzania',
 'Czechoslovakia',
 'Tonga',
 'Tajikistan',
 'Turkmenistan',
 'Togo',
 'Taiwan',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Tuvalu',
 'United Arab Emirates',
 'United Arab Republic',
 'Uganda',
 'Ukraine',
 'Soviet Union',
 'Uruguay',
 'United States of America',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Saint Vincent and Grenadines',
 'North Yemen',
 'Yemen',
 'South Yemen',
 'Yugoslavia',
 'Zambia',
 'Zimbabwe']

# Event codes master list (from Event Codes Hidden)
EVENT_CODES = ['100',
 '200',
 '400',
 '800',
 '1500',
 '3000',
 '5000',
 '10000',
 '80H',
 '100H',
 '110H',
 '200H',
 '400H',
 '2000S',
 '3000S',
 '1500W',
 '3000W',
 '5000W',
 '10000w',
 'SP',
 'JT',
 'DT',
 'HT',
 'LJ',
 'TJ',
 'HJ',
 'PV']

# Event options (from "Event Codes (updated)")
# Each item: gender "M"/"F", division number (1/2/3/4/8), event_name, event_code
# Blacked-out Event Code cells (solid fill where font color matches fill) are excluded.
EVENTS = [{'division': 4, 'event_code': '100', 'event_name': '100m', 'gender': 'M'},
 {'division': 3, 'event_code': '100', 'event_name': '100m', 'gender': 'M'},
 {'division': 2, 'event_code': '100', 'event_name': '100m', 'gender': 'M'},
 {'division': 1, 'event_code': '100', 'event_name': '100m', 'gender': 'M'},
 {'division': 4, 'event_code': '200', 'event_name': '200m', 'gender': 'M'},
 {'division': 3, 'event_code': '200', 'event_name': '200m', 'gender': 'M'},
 {'division': 2, 'event_code': '200', 'event_name': '200m', 'gender': 'M'},
 {'division': 1, 'event_code': '200', 'event_name': '200m', 'gender': 'M'},
 {'division': 4, 'event_code': '400', 'event_name': '400m', 'gender': 'M'},
 {'division': 3, 'event_code': '400', 'event_name': '400m', 'gender': 'M'},
 {'division': 2, 'event_code': '400', 'event_name': '400m', 'gender': 'M'},
 {'division': 1, 'event_code': '400', 'event_name': '400m', 'gender': 'M'},
 {'division': 4, 'event_code': '800', 'event_name': '800m', 'gender': 'M'},
 {'division': 3, 'event_code': '800', 'event_name': '800m', 'gender': 'M'},
 {'division': 2, 'event_code': '800', 'event_name': '800m', 'gender': 'M'},
 {'division': 1, 'event_code': '800', 'event_name': '800m', 'gender': 'M'},
 {'division': 4, 'event_code': '1500', 'event_name': '1500m', 'gender': 'M'},
 {'division': 3, 'event_code': '1500', 'event_name': '1500m', 'gender': 'M'},
 {'division': 2, 'event_code': '1500', 'event_name': '1500m', 'gender': 'M'},
 {'division': 1, 'event_code': '1500', 'event_name': '1500m', 'gender': 'M'},
 {'division': 2, 'event_code': '3000', 'event_name': '3000m', 'gender': 'M'},
 {'division': 1, 'event_code': '3000', 'event_name': '3000m', 'gender': 'M'},
 {'division': 4, 'event_code': '5000', 'event_name': '5000m', 'gender': 'M'},
 {'division': 3, 'event_code': '5000', 'event_name': '5000m', 'gender': 'M'},
 {'division': 4, 'event_code': '10000', 'event_name': '10000m', 'gender': 'M'},
 {'division': 2, 'event_code': '2000s', 'event_name': '2000 Steeplechase (0.838m)', 'gender': 'M'},
 {'division': 4, 'event_code': '3000s', 'event_name': '3000 Steeplechase (0.914m)', 'gender': 'M'},
 {'division': 3, 'event_code': '3000s', 'event_name': '3000 Steeplechase (0.914m)', 'gender': 'M'},
 {'division': 1, 'event_code': '1500W', 'event_name': '1500mWalk', 'gender': 'M'},
 {'division': 2, 'event_code': '3000W', 'event_name': '3000mWalk', 'gender': 'M'},
 {'division': 3, 'event_code': '5000W', 'event_name': '5000mWalk', 'gender': 'M'},
 {'division': 4, 'event_code': '10000W', 'event_name': '10000mWalk', 'gender': 'M'},
 {'division': 1, 'event_code': '100H', 'event_name': '100mH (0.838m)', 'gender': 'M'},
 {'division': 4, 'event_code': '110H', 'event_name': '110mH (1.067m)', 'gender': 'M'},
 {'division': 3, 'event_code': '110H', 'event_name': '110mH (0.991m)', 'gender': 'M'},
 {'division': 2, 'event_code': '110H', 'event_name': '110mH (0.914m)', 'gender': 'M'},
 {'division': 1, 'event_code': '200h', 'event_name': '200mH (.0762m)', 'gender': 'M'},
 {'division': 4, 'event_code': '400h', 'event_name': '400mH (0.914m)', 'gender': 'M'},
 {'division': 3, 'event_code': '400h', 'event_name': '400mH (0.914m)', 'gender': 'M'},
 {'division': 2, 'event_code': '400h', 'event_name': '400mH (0.838m)', 'gender': 'M'},
 {'division': 4, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'M'},
 {'division': 3, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'M'},
 {'division': 2, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'M'},
 {'division': 1, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'M'},
 {'division': 4, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'M'},
 {'division': 3, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'M'},
 {'division': 2, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'M'},
 {'division': 1, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'M'},
 {'division': 4, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'M'},
 {'division': 3, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'M'},
 {'division': 2, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'M'},
 {'division': 1, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'M'},
 {'division': 4, 'event_code': 'TJ', 'event_name': 'Triple Jump (9m, 11m & 13m board)', 'gender': 'M'},
 {'division': 3, 'event_code': 'TJ', 'event_name': 'Triple Jump (9m, 11m & 13m board)', 'gender': 'M'},
 {'division': 2, 'event_code': 'TJ', 'event_name': 'Triple Jump (9m, 10m & 11m board)', 'gender': 'M'},
 {'division': 1, 'event_code': 'TJ', 'event_name': 'Triple Jump (7m, 8m & 9m board)', 'gender': 'M'},
 {'division': 4, 'event_code': 'SP', 'event_name': 'Shot Put (7.26kg)', 'gender': 'M'},
 {'division': 3, 'event_code': 'SP', 'event_name': 'Shot Put (6kg)', 'gender': 'M'},
 {'division': 2, 'event_code': 'SP', 'event_name': 'Shot Put (5kg)', 'gender': 'M'},
 {'division': 1, 'event_code': 'SP', 'event_name': 'Shot Put (4kg)', 'gender': 'M'},
 {'division': 8, 'event_code': 'SP', 'event_name': 'Shot Put (5kg)', 'gender': 'M'},
 {'division': 4, 'event_code': 'DT', 'event_name': 'Discus (2kg)', 'gender': 'M'},
 {'division': 3, 'event_code': 'DT', 'event_name': 'Discus (1.75kg)', 'gender': 'M'},
 {'division': 2, 'event_code': 'DT', 'event_name': 'Discus (1.5kg)', 'gender': 'M'},
 {'division': 1, 'event_code': 'DT', 'event_name': 'Discus (1kg)', 'gender': 'M'},
 {'division': 8, 'event_code': 'DT', 'event_name': 'Discus (1.5kg)', 'gender': 'M'},
 {'division': 4, 'event_code': 'JT', 'event_name': 'Javelin (800g)', 'gender': 'M'},
 {'division': 3, 'event_code': 'JT', 'event_name': 'Javelin (800g)', 'gender': 'M'},
 {'division': 2, 'event_code': 'JT', 'event_name': 'Javelin (700g)', 'gender': 'M'},
 {'division': 1, 'event_code': 'JT', 'event_name': 'Javelin (600g)', 'gender': 'M'},
 {'division': 8, 'event_code': 'JT', 'event_name': 'Javelin (700g)', 'gender': 'M'},
 {'division': 4, 'event_code': 'HT', 'event_name': 'Hammer (7.26kg)', 'gender': 'M'},
 {'division': 3, 'event_code': 'HT', 'event_name': 'Hammer (6kg)', 'gender': 'M'},
 {'division': 8, 'event_code': 'HT', 'event_name': 'Hammer (5kg)', 'gender': 'M'},
 {'division': 4, 'event_code': '100', 'event_name': '100m', 'gender': 'F'},
 {'division': 3, 'event_code': '100', 'event_name': '100m', 'gender': 'F'},
 {'division': 2, 'event_code': '100', 'event_name': '100m', 'gender': 'F'},
 {'division': 1, 'event_code': '100', 'event_name': '100m', 'gender': 'F'},
 {'division': 4, 'event_code': '200', 'event_name': '200m', 'gender': 'F'},
 {'division': 3, 'event_code': '200', 'event_name': '200m', 'gender': 'F'},
 {'division': 2, 'event_code': '200', 'event_name': '200m', 'gender': 'F'},
 {'division': 1, 'event_code': '200', 'event_name': '200m', 'gender': 'F'},
 {'division': 4, 'event_code': '400', 'event_name': '400m', 'gender': 'F'},
 {'division': 3, 'event_code': '400', 'event_name': '400m', 'gender': 'F'},
 {'division': 2, 'event_code': '400', 'event_name': '400m', 'gender': 'F'},
 {'division': 1, 'event_code': '400', 'event_name': '400m', 'gender': 'F'},
 {'division': 4, 'event_code': '800', 'event_name': '800m', 'gender': 'F'},
 {'division': 3, 'event_code': '800', 'event_name': '800m', 'gender': 'F'},
 {'division': 2, 'event_code': '800', 'event_name': '800m', 'gender': 'F'},
 {'division': 1, 'event_code': '800', 'event_name': '800m', 'gender': 'F'},
 {'division': 4, 'event_code': '1500', 'event_name': '1500m', 'gender': 'F'},
 {'division': 3, 'event_code': '1500', 'event_name': '1500m', 'gender': 'F'},
 {'division': 2, 'event_code': '1500', 'event_name': '1500m', 'gender': 'F'},
 {'division': 1, 'event_code': '1500', 'event_name': '1500m', 'gender': 'F'},
 {'division': 3, 'event_code': '3000', 'event_name': '3000m', 'gender': 'F'},
 {'division': 2, 'event_code': '3000', 'event_name': '3000m', 'gender': 'F'},
 {'division': 1, 'event_code': '3000', 'event_name': '3000m', 'gender': 'F'},
 {'division': 4, 'event_code': '5000', 'event_name': '5000m', 'gender': 'F'},
 {'division': 3, 'event_code': '5000', 'event_name': '5000m', 'gender': 'F'},
 {'division': 4, 'event_code': '10000', 'event_name': '10000m', 'gender': 'F'},
 {'division': 3, 'event_code': '2000s', 'event_name': '2000 Steeplechase (0.762m)', 'gender': 'F'},
 {'division': 4, 'event_code': '3000s', 'event_name': '3000 Steeplechase (0.762m)', 'gender': 'F'},
 {'division': 2, 'event_code': '1500W', 'event_name': '1500mWalk', 'gender': 'F'},
 {'division': 1, 'event_code': '1500W', 'event_name': '1500mWalk', 'gender': 'F'},
 {'division': 3, 'event_code': '3000W', 'event_name': '3000mWalk', 'gender': 'F'},
 {'division': 4, 'event_code': '10000W', 'event_name': '10000mWalk', 'gender': 'F'},
 {'division': 1, 'event_code': '80H', 'event_name': '80mH (0.762m)', 'gender': 'F'},
 {'division': 4, 'event_code': '100H', 'event_name': '100mH (0.838m)', 'gender': 'F'},
 {'division': 3, 'event_code': '100H', 'event_name': '100mH (0.838m)', 'gender': 'F'},
 {'division': 2, 'event_code': '100H', 'event_name': '100mH (0.762m)', 'gender': 'F'},
 {'division': 1, 'event_code': '200h', 'event_name': '200mH (0.762m)', 'gender': 'F'},
 {'division': 4, 'event_code': '400h', 'event_name': '400mH (0.762m)', 'gender': 'F'},
 {'division': 3, 'event_code': '400h', 'event_name': '400mH (0.762m)', 'gender': 'F'},
 {'division': 2, 'event_code': '400h', 'event_name': '400mH (0.762m)', 'gender': 'F'},
 {'division': 4, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'F'},
 {'division': 3, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'F'},
 {'division': 2, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'F'},
 {'division': 1, 'event_code': 'HJ', 'event_name': 'High Jump', 'gender': 'F'},
 {'division': 4, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'F'},
 {'division': 3, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'F'},
 {'division': 2, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'F'},
 {'division': 1, 'event_code': 'PV', 'event_name': 'Pole Vault', 'gender': 'F'},
 {'division': 4, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'F'},
 {'division': 3, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'F'},
 {'division': 2, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'F'},
 {'division': 1, 'event_code': 'LJ', 'event_name': 'Long Jump', 'gender': 'F'},
 {'division': 4, 'event_code': 'TJ', 'event_name': 'Triple Jump (9m, 10m & 11m board)', 'gender': 'F'},
 {'division': 3, 'event_code': 'TJ', 'event_name': 'Triple Jump (9m, 10m & 11m board)', 'gender': 'F'},
 {'division': 2, 'event_code': 'TJ', 'event_name': 'Triple Jump (7m, 8m & 9m board)', 'gender': 'F'},
 {'division': 1, 'event_code': 'TJ', 'event_name': 'Triple Jump (6m, 7m & 8m board)', 'gender': 'F'},
 {'division': 4, 'event_code': 'SP', 'event_name': 'Shot Put (4kg)', 'gender': 'F'},
 {'division': 3, 'event_code': 'SP', 'event_name': 'Shot Put (4kg)', 'gender': 'F'},
 {'division': 2, 'event_code': 'SP', 'event_name': 'Shot Put (3kg)', 'gender': 'F'},
 {'division': 1, 'event_code': 'SP', 'event_name': 'Shot Put (3kg)', 'gender': 'F'},
 {'division': 4, 'event_code': 'DT', 'event_name': 'Discus (1kg)', 'gender': 'F'},
 {'division': 3, 'event_code': 'DT', 'event_name': 'Discus (1kg)', 'gender': 'F'},
 {'division': 2, 'event_code': 'DT', 'event_name': 'Discus (1kg)', 'gender': 'F'},
 {'division': 1, 'event_code': 'DT', 'event_name': 'Discus (1kg)', 'gender': 'F'},
 {'division': 4, 'event_code': 'JT', 'event_name': 'Javelin (600g)', 'gender': 'F'},
 {'division': 3, 'event_code': 'JT', 'event_name': 'Javelin (600g)', 'gender': 'F'},
 {'division': 2, 'event_code': 'JT', 'event_name': 'Javelin (500g)', 'gender': 'F'},
 {'division': 1, 'event_code': 'JT', 'event_name': 'Javelin (500g)', 'gender': 'F'},
 {'division': 4, 'event_code': 'HT', 'event_name': 'Hammer (4kg)', 'gender': 'F'},
 {'division': 3, 'event_code': 'HT', 'event_name': 'Hammer (4kg)', 'gender': 'F'}]

def get_team_name(team_code: str) -> str:
    return TEAM_CODE_TO_NAME.get((team_code or "").strip(), "")

# -----------------------------
# Derived event indexes
# -----------------------------

EVENTS_BY_GENDER_DIV = {('F', 1): [('100m', '100'),
            ('1500m', '1500'),
            ('1500mWalk', '1500W'),
            ('200m', '200'),
            ('200mH (0.762m)', '200h'),
            ('3000m', '3000'),
            ('400m', '400'),
            ('800m', '800'),
            ('80mH (0.762m)', '80H'),
            ('Discus (1kg)', 'DT'),
            ('High Jump', 'HJ'),
            ('Javelin (500g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (3kg)', 'SP'),
            ('Triple Jump (6m, 7m & 8m board)', 'TJ')],
 ('F', 2): [('100m', '100'),
            ('100mH (0.762m)', '100H'),
            ('1500m', '1500'),
            ('1500mWalk', '1500W'),
            ('200m', '200'),
            ('3000m', '3000'),
            ('400m', '400'),
            ('400mH (0.762m)', '400h'),
            ('800m', '800'),
            ('Discus (1kg)', 'DT'),
            ('High Jump', 'HJ'),
            ('Javelin (500g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (3kg)', 'SP'),
            ('Triple Jump (7m, 8m & 9m board)', 'TJ')],
 ('F', 3): [('100m', '100'),
            ('100mH (0.838m)', '100H'),
            ('1500m', '1500'),
            ('2000 Steeplechase (0.762m)', '2000s'),
            ('200m', '200'),
            ('3000m', '3000'),
            ('3000mWalk', '3000W'),
            ('400m', '400'),
            ('400mH (0.762m)', '400h'),
            ('5000m', '5000'),
            ('800m', '800'),
            ('Discus (1kg)', 'DT'),
            ('Hammer (4kg)', 'HT'),
            ('High Jump', 'HJ'),
            ('Javelin (600g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (4kg)', 'SP'),
            ('Triple Jump (9m, 10m & 11m board)', 'TJ')],
 ('F', 4): [('10000m', '10000'),
            ('10000mWalk', '10000W'),
            ('100m', '100'),
            ('100mH (0.838m)', '100H'),
            ('1500m', '1500'),
            ('200m', '200'),
            ('3000 Steeplechase (0.762m)', '3000s'),
            ('400m', '400'),
            ('400mH (0.762m)', '400h'),
            ('5000m', '5000'),
            ('800m', '800'),
            ('Discus (1kg)', 'DT'),
            ('Hammer (4kg)', 'HT'),
            ('High Jump', 'HJ'),
            ('Javelin (600g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (4kg)', 'SP'),
            ('Triple Jump (9m, 10m & 11m board)', 'TJ')],
 ('M', 1): [('100m', '100'),
            ('100mH (0.838m)', '100H'),
            ('1500m', '1500'),
            ('1500mWalk', '1500W'),
            ('200m', '200'),
            ('200mH (.0762m)', '200h'),
            ('3000m', '3000'),
            ('400m', '400'),
            ('800m', '800'),
            ('Discus (1kg)', 'DT'),
            ('High Jump', 'HJ'),
            ('Javelin (600g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (4kg)', 'SP'),
            ('Triple Jump (7m, 8m & 9m board)', 'TJ')],
 ('M', 2): [('100m', '100'),
            ('110mH (0.914m)', '110H'),
            ('1500m', '1500'),
            ('2000 Steeplechase (0.838m)', '2000s'),
            ('200m', '200'),
            ('3000m', '3000'),
            ('3000mWalk', '3000W'),
            ('400m', '400'),
            ('400mH (0.838m)', '400h'),
            ('800m', '800'),
            ('Discus (1.5kg)', 'DT'),
            ('High Jump', 'HJ'),
            ('Javelin (700g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (5kg)', 'SP'),
            ('Triple Jump (9m, 10m & 11m board)', 'TJ')],
 ('M', 3): [('100m', '100'),
            ('110mH (0.991m)', '110H'),
            ('1500m', '1500'),
            ('200m', '200'),
            ('3000 Steeplechase (0.914m)', '3000s'),
            ('400m', '400'),
            ('400mH (0.914m)', '400h'),
            ('5000m', '5000'),
            ('5000mWalk', '5000W'),
            ('800m', '800'),
            ('Discus (1.75kg)', 'DT'),
            ('Hammer (6kg)', 'HT'),
            ('High Jump', 'HJ'),
            ('Javelin (800g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (6kg)', 'SP'),
            ('Triple Jump (9m, 11m & 13m board)', 'TJ')],
 ('M', 4): [('10000m', '10000'),
            ('10000mWalk', '10000W'),
            ('100m', '100'),
            ('110mH (1.067m)', '110H'),
            ('1500m', '1500'),
            ('200m', '200'),
            ('3000 Steeplechase (0.914m)', '3000s'),
            ('400m', '400'),
            ('400mH (0.914m)', '400h'),
            ('5000m', '5000'),
            ('800m', '800'),
            ('Discus (2kg)', 'DT'),
            ('Hammer (7.26kg)', 'HT'),
            ('High Jump', 'HJ'),
            ('Javelin (800g)', 'JT'),
            ('Long Jump', 'LJ'),
            ('Pole Vault', 'PV'),
            ('Shot Put (7.26kg)', 'SP'),
            ('Triple Jump (9m, 11m & 13m board)', 'TJ')],
 ('M', 8): [('Discus (1.5kg)', 'DT'), ('Hammer (5kg)', 'HT'), ('Javelin (700g)', 'JT'), ('Shot Put (5kg)', 'SP')]}

EVENTS_BY_DIV = {1: ['100m',
     '100mH (0.838m)',
     '1500m',
     '1500mWalk',
     '200m',
     '200mH (.0762m)',
     '200mH (0.762m)',
     '3000m',
     '400m',
     '800m',
     '80mH (0.762m)',
     'Discus (1kg)',
     'High Jump',
     'Javelin (500g)',
     'Javelin (600g)',
     'Long Jump',
     'Pole Vault',
     'Shot Put (3kg)',
     'Shot Put (4kg)',
     'Triple Jump (6m, 7m & 8m board)',
     'Triple Jump (7m, 8m & 9m board)'],
 2: ['100m',
     '100mH (0.762m)',
     '110mH (0.914m)',
     '1500m',
     '1500mWalk',
     '2000 Steeplechase (0.838m)',
     '200m',
     '3000m',
     '3000mWalk',
     '400m',
     '400mH (0.762m)',
     '400mH (0.838m)',
     '800m',
     'Discus (1.5kg)',
     'Discus (1kg)',
     'High Jump',
     'Javelin (500g)',
     'Javelin (700g)',
     'Long Jump',
     'Pole Vault',
     'Shot Put (3kg)',
     'Shot Put (5kg)',
     'Triple Jump (7m, 8m & 9m board)',
     'Triple Jump (9m, 10m & 11m board)'],
 3: ['100m',
     '100mH (0.838m)',
     '110mH (0.991m)',
     '1500m',
     '2000 Steeplechase (0.762m)',
     '200m',
     '3000 Steeplechase (0.914m)',
     '3000m',
     '3000mWalk',
     '400m',
     '400mH (0.762m)',
     '400mH (0.914m)',
     '5000m',
     '5000mWalk',
     '800m',
     'Discus (1.75kg)',
     'Discus (1kg)',
     'Hammer (4kg)',
     'Hammer (6kg)',
     'High Jump',
     'Javelin (600g)',
     'Javelin (800g)',
     'Long Jump',
     'Pole Vault',
     'Shot Put (4kg)',
     'Shot Put (6kg)',
     'Triple Jump (9m, 10m & 11m board)',
     'Triple Jump (9m, 11m & 13m board)'],
 4: ['10000m',
     '10000mWalk',
     '100m',
     '100mH (0.838m)',
     '110mH (1.067m)',
     '1500m',
     '200m',
     '3000 Steeplechase (0.762m)',
     '3000 Steeplechase (0.914m)',
     '400m',
     '400mH (0.762m)',
     '400mH (0.914m)',
     '5000m',
     '800m',
     'Discus (1kg)',
     'Discus (2kg)',
     'Hammer (4kg)',
     'Hammer (7.26kg)',
     'High Jump',
     'Javelin (600g)',
     'Javelin (800g)',
     'Long Jump',
     'Pole Vault',
     'Shot Put (4kg)',
     'Shot Put (7.26kg)',
     'Triple Jump (9m, 10m & 11m board)',
     'Triple Jump (9m, 11m & 13m board)'],
 8: ['Discus (1.5kg)', 'Hammer (5kg)', 'Javelin (700g)', 'Shot Put (5kg)']}

def get_event_names_for_division(division: int):
    """Return a sorted list of event_name values available for a division (across genders)."""
    return list(EVENTS_BY_DIV.get(int(division), []))

def get_event_options(division: int, gender: str | None = None, include_gender_suffix: bool = False):
    """Return event dropdown options.

    If gender is provided ("M" or "F"), returns list of (event_name, event_code) for that gender+division.

    If gender is None, returns list of (label, event_code) across both genders:
      - label is event_name (or "event_name [M/F]" if include_gender_suffix=True)
      - event_code comes from the source mapping for that gender.
    """
    d = int(division)
    if gender:
        g = (gender or "").strip().upper()
        return list(EVENTS_BY_GENDER_DIV.get((g, d), []))

    out = []
    for g in ("M", "F"):
        for name, code in EVENTS_BY_GENDER_DIV.get((g, d), []):
            label = f"EVENTS [F]" if include_gender_suffix else name
            out.append((label, code))
    out.sort(key=lambda x: x[0])
    return out

def get_events(gender: str, division: int):
    """Backward-compatible wrapper (gender + division)."""
    return get_event_options(division=int(division), gender=(gender or "").strip().upper())
